### ISSUE TITLE
servidor hamachi

### ISSUE THREAD

**Issue by pedroaugusto1923** [FiveMP/FiveMP#11]
suporte a servidor de hamachi

**Comment by pedroaugusto1923** [comment]
gta vmp rip :(

**Comment by FiveMP** [comment]
Hi there,

Could you give us more details on what exactly is not working together with Hamachi? It has always worked for FiveMP. Are you sure that you're setting the correct Hamachi IP address in your FiveMP.ini?

Thanks,
Dev
