### ISSUE TITLE
Player Names become malformed on death.

### ISSUE THREAD

**Issue by No-Half-Measures** [FiveMP/FiveMP#19]
![f90b9f444ae749ada0fb2fecdf1ddcb4](https://cloud.githubusercontent.com/assets/916733/16815215/d7e8c784-4930-11e6-8953-45553110b294.png)
![unknown](https://cloud.githubusercontent.com/assets/916733/16815216/d8087746-4930-11e6-8222-5d95c5069fc3.png)

**Comment by FiveMP** [comment]
Fixed in 3a2772a73fc5103359f5d3e49938689cf3682137.
Thanks for reporting!
