### ISSUE TITLE
Additional Include & Library Paths

### ISSUE THREAD

**Issue by No-Half-Measures** [FiveMP/FiveMP#2]
If someone wishes too contribute they would have to change the Additional Include path to match where their project is located which as you could imagine will cause the _vcxproj_ file to be diffrent with everyone.
If you change them to be relative to the project then this wouldn't be the case and will save anyone the headache of trying to figure out why some includes aren't being found.

**For FiveMP_Client:**
> ../../Vendor\jitasm;../../FiveMP_Launcher\FiveMP_Client;../../Vendor\inih;../../Vendor\RakNet;../../Vendor\hooking;%(AdditionalIncludeDirectories)

**For FiveMP_Server:**
> ../../Vendor\inih;../../Vendor\RakNet;%(AdditionalIncludeDirectories)

The same for the Additional Library

**For FiveMP_Client**
> ../../lib;%(AdditionalLibraryDirectories)

Also is the 'ScriptHookV.lib' meant to be not in the repo?

**Comment by FiveMP** [comment]
both fixed and committed, thanks.
