### ISSUE TITLE
Connect to a Different Server In-Game

### ISSUE THREAD

**Issue by MuhsinunCool** [FiveMP/FiveMP#6]
Title says it all. Perhaps through console for now but as the mod gets more mature maybe an in-game GUI like in gtavmp? Thanks!

**Comment by FiveMP** [comment]
GUI is hoping to be implemented somewhere around 0.2a or even earlier. There'll probably be a button to reload the config file next version, thanks!

**Comment by MuhsinunCool** [comment]
:D yay! ty!

**Comment by FiveMP** [comment]
Issue resolved in bec68dcbaa95ca3777b9278d9d14723d2df9fcd7 - will be featured in the next Release Candidate.
